# Basic Site Settings
locale                   : "en-US"
site_theme               : "default"
title                    : "Huailiang Ma"
title_separator          : "-"
name                     : &name "Huailiang Ma"
description              : &description "Research on imitation learning, dataset generation, robotic teleoperation"
url                      : "https://huailiangma.github.io"
baseurl                  : ""
repository               : "HuailiangMa/HuailiangMa.github.io"

# Sidebar Author Info
author:
  avatar           : "profile.png"
  name             : "Huailiang Ma"
  pronouns         : 
  bio              : "Master’s student at Southeast University. Research in imitation learning, dataset generation, robotic teleoperation."
  location         : "Nanjing, China"
  employer         : "Southeast University"
  uri              : 
  email            : "your_email@seu.edu.cn"

  # Academic websites
  academia         : 
  arxiv            : 
  googlescholar    : "https://scholar.google.com.hk/citations?user=HsrhHWIAAAAJ"
  inspire-hep      : 
  impactstory      : 
  orcid            : 
  semantic         : 
  pubmed           : 
  researchgate     : 
  scopus           : 

  # Repositories
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "https://github.com/HuailiangMa"
  kaggle           : 
  stackoverflow    : 

  # Social media
  artstation       : 
  bluesky          : 
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : 
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : 
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : "https://blog.csdn.net/qq_53186375"
